services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENV=dev


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./apps/frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
